### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by Sohil** [kucherenko/jscpd#162]
I get the following error when i try to run the jscpd command 
Please note I'm running on a mac OS. 

`$ cd ios-code/
$ jscpd
info:    jscpd - copy/paste detector for programming source code, developed by Andrey Kucherenko
info:    Preprocessors running time: durationMs=1241
info:    Scanning 3163 files for duplicates...
fs.js:733
  var r = binding.read(fd, buffer, offset, length, position);
                  ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:733:19)
    at tryReadSync (fs.js:488:20)
    at Object.fs.readFileSync (fs.js:536:19)
    at Strategy.detect (/usr/local/lib/node_modules/jscpd/lib/strategy.js:32:19)
    at Detector.start (/usr/local/lib/node_modules/jscpd/lib/detector.js:17:23)
    at JsCpd.run (/usr/local/lib/node_modules/jscpd/lib/jscpd.js:45:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/jscpd/lib/cli/cli.js:52:11)
    at Object.cli.main (/usr/local/lib/node_modules/jscpd/node_modules/cli/cli.js:957:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/jscpd/lib/cli/cli.js:47:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/jscpd/lib/cli/cli.js:56:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)`

**Comment by kucherenko** [comment]
Thank you for reporting, try to use the new version of jscpd with the following command
```
npx jscpd@1.0.0-alpha.2
```

I will investigate the issue and fix if it is possible

**Comment by lisez** [comment]
I have the same issue. This is because that some folder's name has an ext-like suffix, such as 'normalize.css'. I have made a PR.

**Comment by maxkomarychev** [comment]
hey @kucherenko, it seems like issue is still here:

```
$ jscpd -v
jscpd v0.6.25
```
this is how I launch it:

```
jscpd --path src --languages=css,javascript,jsx --reporter=json --output=report
```

directory `report` exists.
