### ISSUE TITLE
UnhandledPromiseRejectionWarning when analyzing JavaScript file

### ISSUE THREAD

**Issue by dubst3pp4** [kucherenko/jscpd#192]
Hello,

I've just installed jscpd and tried to analyze a JavaScript file:

`jscpd assets/controller.rates.js`

When I run this I get the following error:

`(node:11079) UnhandledPromiseRejectionWarning: Error: ENOTDIR: not a directory, scandir '/home/marc/WebProjects/XTO/html/modules/contracts/view/edit/assets/js/controller.rates.js'
    at Object.fs.readdirSync (fs.js:904:18)
    at exports.readdir (/home/marc/.npm-global/lib/node_modules/jscpd/node_modules/@mrmlnc/readdir-enhanced/lib/sync/fs.js:18:20)
    at Object.safeCall [as safe] (/home/marc/.npm-global/lib/node_modules/jscpd/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:24:8)
    at DirectoryReader.readNextDirectory (/home/marc/.npm-global/lib/node_modules/jscpd/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:78:10)
    at Readable.DirectoryReader.stream._read (/home/marc/.npm-global/lib/node_modules/jscpd/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:57:18)
    at Readable.read (_stream_readable.js:442:10)
    at readdirSync (/home/marc/.npm-global/lib/node_modules/jscpd/node_modules/@mrmlnc/readdir-enhanced/lib/sync/index.js:27:21)
    at Function.readdirSyncStat (/home/marc/.npm-global/lib/node_modules/jscpd/node_modules/@mrmlnc/readdir-enhanced/lib/index.js:34:10)
    at ReaderSync.dynamicApi (/home/marc/.npm-global/lib/node_modules/jscpd/node_modules/fast-glob/out/providers/reader-sync.js:64:24)
    at ReaderSync.api (/home/marc/.npm-global/lib/node_modules/jscpd/node_modules/fast-glob/out/providers/reader-sync.js:56:25)
(node:11079) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11079) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I'm wondering why jscpd stumbles upon this file, as it is just a regular JavaScript source file?!

Thanks for any hint :-)

**Desktop:**
 - OS: Linux
 - OS Version: Ubuntu 18.04LTS, Kernel 4.15
 - NodeJS Version 8.15.0
 - jscpd version 2.0.4

**Comment by dubst3pp4** [comment]
Btw. this also happens with PHP files.

**Comment by kucherenko** [comment]
Thank you for the report, currently, you should point just path to the directory with files, not single file

**Comment by kucherenko** [comment]
fixed at jscpd@2.0.5
