### ISSUE TITLE
Cannot read property 'loc' of undefined when passing -k

### ISSUE THREAD

**Issue by nafg** [kucherenko/jscpd#208]
```
$ jscpd -k 50 src/
(node:2755) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'loc' of undefined
    at Object.<anonymous> (/home/naftoli/bin/npm/lib/node_modules/jscpd/build/clone/index.js:61:49)
    at step (/home/naftoli/bin/npm/lib/node_modules/jscpd/build/clone/index.js:32:23)
    at Object.next (/home/naftoli/bin/npm/lib/node_modules/jscpd/build/clone/index.js:13:53)
    at fulfilled (/home/naftoli/bin/npm/lib/node_modules/jscpd/build/clone/index.js:4:58)
(node:2755) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2755) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kucherenko** [comment]
fixed at jscpd@2.0.11
