### ISSUE TITLE
Issue when analyzing code

### ISSUE THREAD

**Issue by juli1** [kucherenko/jscpd#225]
**Describe the bug**

**To Reproduce**
1. Clone https://github.com/osate/osate2.git
2. Run jscpd on it

You get the error:
```
(node:5198) UnhandledPromiseRejectionWarning: TypeError: name.replace is not a function
    at sanitizeLangName (/usr/local/lib/node_modules/jscpd/build/tokenizer/prism.js:62:21)
    at /usr/local/lib/node_modules/jscpd/build/tokenizer/prism.js:90:109
    at Array.forEach (<anonymous>)
    at createTokens (/usr/local/lib/node_modules/jscpd/build/tokenizer/prism.js:90:27)
    at /usr/local/lib/node_modules/jscpd/build/tokenizer/prism.js:60:137
    at Array.forEach (<anonymous>)
    at Object.tokenize (/usr/local/lib/node_modules/jscpd/build/tokenizer/prism.js:60:83)
    at JSCPD.<anonymous> (/usr/local/lib/node_modules/jscpd/build/jscpd.js:302:46)
    at step (/usr/local/lib/node_modules/jscpd/build/jscpd.js:43:23)
    at Object.next (/usr/local/lib/node_modules/jscpd/build/jscpd.js:24:53)
(node:5198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:5198) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Expected behavior**
Program should terminate without error

**Desktop (please complete the following information):**
Ubuntu
JSCPD 2.0.13

**Comment by kucherenko** [comment]
Duplicated issue https://github.com/kucherenko/jscpd/issues/223
