### ISSUE TITLE
jscpd not working on node 6.x

### ISSUE THREAD

**Issue by dimofeev** [kucherenko/jscpd#247]
**Describe the bug**
JSCPD tool is not working on node 6.x

**To Reproduce**
1. Run node 6.x
2. Start the jscpd

**Error**
TypeError: Object.values is not a function
    at JSCPD.initializeListeners (/home/travis/build/Kinvey/flex-sdk/node_modules/jscpd/build/jscpd.js:341:16)
    at new JSCPD (/home/travis/build/Kinvey/flex-sdk/node_modules/jscpd/build/jscpd.js:119:14)
    at Object.<anonymous> (/home/travis/build/Kinvey/flex-sdk/node_modules/jscpd/build/cli.js:49:11)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)

**Comment by kucherenko** [comment]
Thank you for the report, I will investigate. As a temporary solution I can suggest use jscpd@0.6.x

**Comment by dimofeev** [comment]
Thank you, @kucherenko

**Comment by kucherenko** [comment]
I've investigated the issue and can suggest use old version of jscpd (0.6.x) because I can't add support of node 6.x from security perspective
