### ISSUE TITLE
Error: Module (type: reporter) "jscpd-eporters-reporter" does not found,

### ISSUE THREAD

**Issue by lichanghong** [kucherenko/jscpd#285]
命令：
jscpd \
--ignore  $excludePath \
-reporters html \
-output jscpd-output \
--format "objectivec" \
 $cpd_proj_path 

报错：
/usr/local/lib/node_modules/jscpd/build/utils/use.js:32
        throw new Error("Module (type: " + type + ") \"" + packageName + "\" does not found, please check that you have installed the package");
        ^

Error: Module (type: reporter) "jscpd-eporters-reporter" does not found, please check that you have installed the package
    at use (/usr/local/lib/node_modules/jscpd/build/utils/use.js:32:15)
    at Object.useReporter (/usr/local/lib/node_modules/jscpd/build/utils/use.js:17:12)
    at /usr/local/lib/node_modules/jscpd/build/reporters/index.js:38:57
    at Array.forEach (<anonymous>)
    at Object.registerReportersByName (/usr/local/lib/node_modules/jscpd/build/reporters/index.js:37:15)
    at JSCPD.initializeReporters (/usr/local/lib/node_modules/jscpd/build/jscpd.js:333:21)
    at new JSCPD (/usr/local/lib/node_modules/jscpd/build/jscpd.js:120:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/jscpd/build/cli.js:49:11)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)

安装方式：
 npm install -g jscpd

**Comment by kucherenko** [comment]
Hi, looks like you have not jscpd-eporters-reporter, did you install it?

**Comment by lichanghong** [comment]
> Hi, looks like you have not jscpd-eporters-reporter, did you install it?

yeah，I have install it
I have resolve this problem,the reason is -output , I have to replace - to --
