### ISSUE TITLE
JSCPD crashes

### ISSUE THREAD

**Issue by juli1** [kucherenko/jscpd#374]
**Describe the bug**

Running jscpd and got this bug

```
/ecs/task-backend-executor ecs/container-backend-executor/9edd070b-da46-4586-b27a-6bf6031910d5 TypeError: Cannot destructure property `path` of 'undefined' or 'null'.
/ecs/task-backend-executor ecs/container-backend-executor/9edd070b-da46-4586-b27a-6bf6031910d5     at detect (/usr/lib/node_modules/jscpd/node_modules/@jscpd/finder/dist/in-files-detector.js:41:39)
/ecs/task-backend-executor ecs/container-backend-executor/9edd070b-da46-4586-b27a-6bf6031910d5     at InFilesDetector.detect (/usr/lib/node_modules/jscpd/node_modules/@jscpd/finder/dist/in-files-detector.js:65:16)
/ecs/task-backend-executor ecs/container-backend-executor/9edd070b-da46-4586-b27a-6bf6031910d5     at Object.jscpd (/usr/lib/node_modules/jscpd/dist/index.js:46:25)
/ecs/task-backend-executor ecs/container-backend-executor/9edd070b-da46-4586-b27a-6bf6031910d5     at Object.<anonymous> (/usr/lib/node_modules/jscpd/bin/jscpd:15:12)
/ecs/task-backend-executor ecs/container-backend-executor/9edd070b-da46-4586-b27a-6bf6031910d5     at Module._compile (internal/modules/cjs/loader.js:778:30)
/ecs/task-backend-executor ecs/container-backend-executor/9edd070b-da46-4586-b27a-6bf6031910d5     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
/ecs/task-backend-executor ecs/container-backend-executor/9edd070b-da46-4586-b27a-6bf6031910d5     at Module.load (internal/modules/cjs/loader.js:653:32)
/ecs/task-backend-executor ecs/container-backend-executor/9edd070b-da46-4586-b27a-6bf6031910d5     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
/ecs/task-backend-executor ecs/container-backend-executor/9edd070b-da46-4586-b27a-6bf6031910d5     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
/ecs/task-backend-executor ecs/container-backend-executor/9edd070b-da46-4586-b27a-6bf6031910d5     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```

**Expected behavior**

JSCPD to complete

**Screenshots**

**Desktop (please complete the following information):**
 ubuntu/linux
 node 10
 jscpd 3.3.0

**Comment by kucherenko** [comment]
fixed at jscpd@3.3.1
