### ISSUE TITLE
Invalid XML format

### ISSUE THREAD

**Issue by juli1** [kucherenko/jscpd#375]
**Describe the bug**
When parsing binary code that is reported in the XML output, it can lead to parsing issue.

The generated XML files are like this

```
<codefragment><![CDATA[
 --- insert-binary-content-here ---
]]></codefragment>
```

Sometimes, the binary content contains characters that corrupt the XML format and makes it unreadable.

To parse the content, I used the following Python code

```
content = open('out.xml').read()
d = xmltodict.parse(content)
````

I then get an error like this

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/julien/git/ci-backend-executor/venv/lib/python3.7/site-packages/xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 44144, column 39
```

The very same issue is reported by `xmllint`

**To Reproduce**

Code that I used to reproduce this bug is not public and cannot provide clear instructions.

**Expected behavior**
The generated XML file should work.

**Desktop (please complete the following information):**
 - OS: ubuntu
 - NodeJS Version 10
 - jscpd version 3.3.0

**Comment by kucherenko** [comment]
Fixed in [v5.2.1](https://github.com/kucherenko/jscpd/releases/tag/v5.2.1).

The XML reporter now replaces characters XML 1.0 cannot carry (an ANSI escape, a form feed) with U+FFFD, splits any `]]>` inside a fragment across two CDATA sections so the snippet text reads back unchanged, and escapes attribute values once instead of twice. `xmllint --noout` and a strict parser accept the report where they previously refused it with `PCDATA invalid Char value 27`.

There is a runnable demo under `fixtures/xml-report-demo/`. Thank you for the report, and apologies for how long this one sat.
