### ISSUE TITLE
jscpd doesn't handle naughty strings correctly

### ISSUE THREAD

**Issue by snowe2010** [kucherenko/jscpd#427]
**Describe the bug**
Recently started getting this error when testing my 'naughty strings' list. Seems like jscpd doesn't handle naughty strings very well 😉 

build [here](https://github.com/snowe2010/pretty-print/runs/2053236525?check_suite_focus=true)

```
2021-03-08 02:51:49 [INFO]   File:[/github/workspace/src/test/resources/naughty_string_printed.txt]
2021-03-08 02:51:50 [ERROR]   Found errors in [jscpd] linter!
2021-03-08 02:51:50 [ERROR]   Error code: 1. Command output:
------
TypeError: Cannot read property 'length' of undefined
    at calculateLocation (/node_modules/@jscpd/tokenizer/dist/tokenize.js:72:59)
    at /node_modules/@jscpd/tokenizer/dist/tokenize.js:115:32
    at Array.map (<anonymous>)
    at tokenize (/node_modules/@jscpd/tokenizer/dist/tokenize.js:115:10)
    at Object.createTokenMapBasedOnCode (/node_modules/@jscpd/tokenizer/dist/tokenize.js:120:20)
    at Tokenizer.generateMaps (/node_modules/@jscpd/tokenizer/dist/index.js:12:27)
    at Detector.<anonymous> (/node_modules/@jscpd/core/dist/detector.js:33:46)
    at Generator.next (<anonymous>)
    at /node_modules/@jscpd/core/dist/detector.js:8:71
    at new Promise (<anonymous>)
------
2021-03-08 02:51:50 [INFO]   ---------------------------
2021-03-08 02:51:50 [INFO]   File:[/github/workspace/src/test/resources/naughty_strings.json]
2021-03-08 02:51:51 [INFO]    - File:[naughty_strings.json] was linted with [jscpd] successfully
```

here is [`naughty_strings_printed.txt`](https://github.com/snowe2010/pretty-print/blob/05b0b54dd19e4dce2f678c6c5438240d0d7ae405/src/test/resources/naughty_string_printed.txt)

if you want to see the unicode characters before the file is written literally you can view that [here](https://github.com/snowe2010/pretty-print/blob/05b0b54dd19e4dce2f678c6c5438240d0d7ae405/src/test/resources/naughty_strings.json#L11).

**To Reproduce**
1. add the above `naughty_string_printed.txt` to a repo
2. lint? using Super Linter

**Expected behavior**
Shouldn't have linting errors. This is a testing file in a resources directory, meant to test that my library handles naughty strings correctly. 

**Additional context**
not sure what line it's failing on and I don't have the project setup to test locally. I'm getting this error in Github Actions.

**Comment by kucherenko** [comment]
Thank you, will investigate the issue

**Comment by kucherenko** [comment]
please use jscpd@3.3.25, the issue has been fixed

```
npx jscpd@3.3.25 .
```
