### ISSUE TITLE
Crashes when run with -r switch 

### ISSUE THREAD

**Issue by borys-pc33** [kucherenko/jscpd#501]
**Describe the bug**
CLI crashes when run with -r switch

**To Reproduce**
1. Install version 
2. run jscpd --reporters

**Expected behavior**
See reporters that I have

**Actual behaviour**
**Screenshots**
TypeError: cli.reporters.split is not a function
    at convertCliToOptions (C:\Users\borys\AppData\Roaming\npm\node_modules\jscpd\dist\options.js:38:42)
    at Object.prepareOptions (C:\Users\borys\AppData\Roaming\npm\node_modules\jscpd\dist\options.js:86:24)
    at Object.<anonymous> (C:\Users\borys\AppData\Roaming\npm\node_modules\jscpd\dist\index.js:53:32)
    at Generator.next (<anonymous>)
    at C:\Users\borys\AppData\Roaming\npm\node_modules\jscpd\dist\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\borys\AppData\Roaming\npm\node_modules\jscpd\dist\index.js:4:12)
    at Object.jscpd (C:\Users\borys\AppData\Roaming\npm\node_modules\jscpd\dist\index.js:50:12)
    at Object.<anonymous> (C:\Users\borys\AppData\Roaming\npm\node_modules\jscpd\bin\jscpd:15:12)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS Version 21H1
 - NodeJS Version: v14.15.1
 - jscpd version tried 3.4.1 and 3.4.2 installed globally

**Additional context**

**Comment by kucherenko** [comment]
Thank you for the report, in the documentation you can find options for -r parameter, for example you can use html reporter

```
jscpd -r html .
```
The empty reporter does not work
