### ISSUE TITLE
Error when using config file (even example given in readme) but works using command line options

### ISSUE THREAD

**Issue by guenam** [kucherenko/jscpd#98]
Hi,

I got this error:

```
C:\Users\guenael\AppData\Local\Yarn\config\global\node_modules\jscpd\lib\tokenizer\TokenizerFactory.js:56
          result.push.apply(result, TokenizerFactory.prototype.LANGUAGES[language]);
                      ^

TypeError: CreateListFromArrayLike called on non-object
    at TokenizerFactory.getExtensionsByLanguages (C:\Users\guenael\AppData\Local\Yarn\config\global\node_modules\jscpd\lib\tokenizer\TokenizerFactory.js:56:23)
    at prepareOptions (C:\Users\guenael\AppData\Local\Yarn\config\global\node_modules\jscpd\lib\preprocessors\options.js:41:56)
    at optionsPreprocessor (C:\Users\guenael\AppData\Local\Yarn\config\global\node_modules\jscpd\lib\preprocessors\options.js:80:15)
    at JsCpd.execPreProcessors (C:\Users\guenael\AppData\Local\Yarn\config\global\node_modules\jscpd\lib\jscpd.js:33:9)
    at JsCpd.run (C:\Users\guenael\AppData\Local\Yarn\config\global\node_modules\jscpd\lib\jscpd.js:41:12)
    at Object.<anonymous> (C:\Users\guenael\AppData\Local\Yarn\config\global\node_modules\jscpd\lib\cli\cli.js:43:11)
    at Object.cli.main (C:\Users\guenael\AppData\Local\Yarn\config\global\node_modules\cli\cli.js:957:14)
    at Object.<anonymous> (C:\Users\guenael\AppData\Local\Yarn\config\global\node_modules\jscpd\lib\cli\cli.js:38:7)
    at Object.<anonymous> (C:\Users\guenael\AppData\Local\Yarn\config\global\node_modules\jscpd\lib\cli\cli.js:47:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```
OS: Win 10
Typescript v3.4.2
Node v6.11.0

I just spent two hours trying different options and looking online for a solution, so it feels like there is an issue.

**Comment by kucherenko** [comment]
Hi, thank you for reporting. Could you please provide more details about the issue? As I can see you are going to call jscpd from code, am I right?

**Comment by evilebottnawi** [comment]
@kucherenko i have this error too.
Config:
```shell
languages:
  - javascript
  - jsx
  - php
  - css
  - sass
  - htmlmixed   # html mixed source like knockout.js templates
  - yaml
  - xml

exclude:
  - "build/**"
  - "coverage/**"
  - "**/node_modules/**"
  - "**/vendor/**"
  - "**/*.min.*"

reporter: json

languages-exts:
  javascript:
    es
    es5
    es6
    es7
```

**Comment by evilebottnawi** [comment]
Change `languages-exts` to
```yaml
languages-exts:
  javascript:
    - es
    - es5
    - es6
    - es7
```
fixed problem, seems README contain invalid example of config

**Comment by kucherenko** [comment]
thank you for report
README fixed
